version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: markdown-it
    versions:
    - 12.0.4
    - 12.0.5
  - dependency-name: markdown-it-anchor
    versions:
    - 7.0.1
    - 7.0.2
  - dependency-name: hexo
    versions:
    - 5.3.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: hexo-lazyload-image
    versions:
    - 1.0.9
  - dependency-name: hexo-deployer-git
    versions:
    - 2.1.0
